export enum PermissionKey {
  CREATE_PURCHASE_REQUEST = "CREATE_PURCHASE_REQUEST",
  EDIT_PURCHASE_REQUEST = "EDIT_PURCHASE_REQUEST",
  CANCEL_PURCHASE_REQUEST = "CANCEL_PURCHASE_REQUEST",
  VIEW_PURCHASE_REQUEST = "VIEW_PURCHASE_REQUEST",
  APPROVE_PURCHASE_REQUEST = "APPROVE_PURCHASE_REQUEST",
  MOVE_TICKET = "MOVE_TICKET",
  RESOLVE_TICKET = "RESOLVE_TICKET",
  CANCEL_TICKET = "CANCEL_TICKET",
  DELETE_TICKET = "DELETE_TICKET",
  COMMENT_TICKET = "COMMENT_TICKET",
  ATTACH_FILES = "ATTACH_FILES",
  VIEW_TICKET = "VIEW_TICKET",
  VIEW_ARCHIVED_TICKETS = "VIEW_ARCHIVED_TICKETS",
  EXPORT_INVOICES = "EXPORT_INVOICES",
  CREATE_TAG = "CREATE_TAG",
  VIEW_DEVICE = "VIEW_DEVICE",
  CREATE_DEVICE = "CREATE_DEVICE",
  EDIT_DEVICE = "EDIT_DEVICE",
  DELETE_DEVICE = "DELETE_DEVICE",
  REGISTER_DEVICE_MAINTENANCE = "REGISTER_DEVICE_MAINTENANCE",
  MANAGE_USERS = "MANAGE_USERS",
  MANAGE_DEPARTMENTS = "MANAGE_DEPARTMENTS",
  MANAGE_SETTINGS = "MANAGE_SETTINGS",
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
  MANAGE_REQUEST_TYPES = "MANAGE_REQUEST_TYPES",
  CREATE_REQUEST = "CREATE_REQUEST",
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
}

/**
 * Origem de um Tipo de Solicitação: DYNAMIC é qualquer tipo cadastrado pelo
 * administrador (formulário construído a partir de RequestField, gera Ticket
 * direto ao ser enviado, sem aprovação). PURCHASE_REQUEST identifica o
 * registro semente que representa a Solicitação de Compra — existe só pra ela
 * aparecer como card em "Nova Solicitação"; nunca é usado pra renderizar
 * formulário nem validar dado nenhum (a Compra continua 100% no fluxo antigo).
 */
export enum RequestTypeSourceKind {
  DYNAMIC = "DYNAMIC",
  PURCHASE_REQUEST = "PURCHASE_REQUEST",
}

export enum RequestFieldType {
  TEXT = "TEXT",
  TEXTAREA = "TEXTAREA",
  NUMBER = "NUMBER",
  DATE = "DATE",
  SELECT = "SELECT",
  MULTISELECT = "MULTISELECT",
  CHECKBOX = "CHECKBOX",
  FILE = "FILE",
}

export enum PurchaseRequestStatus {
  DRAFT = "DRAFT",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}

export enum TicketStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  CANCELLED = "CANCELLED",
}

export enum Priority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum NotificationPreference {
  EMAIL_ONLY = "EMAIL_ONLY",
  INTERNAL_ONLY = "INTERNAL_ONLY",
  BOTH = "BOTH",
}

export enum NotificationType {
  NEW_TICKET = "NEW_TICKET",
  NEW_COMMENT = "NEW_COMMENT",
  NEW_ATTACHMENT = "NEW_ATTACHMENT",
  NEW_INVOICE_NOTE = "NEW_INVOICE_NOTE",
  TICKET_MOVED = "TICKET_MOVED",
  TICKET_RESOLVED = "TICKET_RESOLVED",
  TICKET_CANCELLED = "TICKET_CANCELLED",
  TICKET_REOPENED = "TICKET_REOPENED",
  NEW_FOLLOWER = "NEW_FOLLOWER",
  REQUEST_APPROVED = "REQUEST_APPROVED",
  REQUEST_REJECTED = "REQUEST_REJECTED",
  REQUEST_PENDING_APPROVAL = "REQUEST_PENDING_APPROVAL",
}

export enum HistoryAction {
  CREATED = "CREATED",
  COMMENTED = "COMMENTED",
  ATTACHMENT_ADDED = "ATTACHMENT_ADDED",
  ATTACHMENT_REMOVED = "ATTACHMENT_REMOVED",
  PRIORITY_CHANGED = "PRIORITY_CHANGED",
  STATUS_CHANGED = "STATUS_CHANGED",
  ASSIGNEE_CHANGED = "ASSIGNEE_CHANGED",
  CANCELLED = "CANCELLED",
  REOPENED = "REOPENED",
  RESOLVED = "RESOLVED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  FOLLOWER_ADDED = "FOLLOWER_ADDED",
  FOLLOWER_REMOVED = "FOLLOWER_REMOVED",
  SUBMITTED_FOR_APPROVAL = "SUBMITTED_FOR_APPROVAL",
  ARCHIVED = "ARCHIVED",
  UNARCHIVED = "UNARCHIVED",
  TAG_ADDED = "TAG_ADDED",
  TAG_REMOVED = "TAG_REMOVED",
}

export enum AuditAction {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  UPLOAD = "UPLOAD",
  DOWNLOAD = "DOWNLOAD",
  COMMENT = "COMMENT",
  MOVE = "MOVE",
  STATUS_CHANGE = "STATUS_CHANGE",
  PERMISSION_CHANGE = "PERMISSION_CHANGE",
}
