import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1700000000000 implements MigrationInterface {
    name = 'InitialSchema1700000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pgcrypto"`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_key_enum" AS ENUM('CREATE_PURCHASE_REQUEST', 'EDIT_PURCHASE_REQUEST', 'CANCEL_PURCHASE_REQUEST', 'VIEW_PURCHASE_REQUEST', 'APPROVE_PURCHASE_REQUEST', 'MOVE_TICKET', 'RESOLVE_TICKET', 'CANCEL_TICKET', 'DELETE_TICKET', 'COMMENT_TICKET', 'ATTACH_FILES', 'VIEW_TICKET', 'VIEW_ARCHIVED_TICKETS', 'EXPORT_INVOICES', 'MANAGE_USERS', 'MANAGE_DEPARTMENTS', 'MANAGE_SETTINGS', 'SYSTEM_ADMIN')`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" "public"."permissions_key_enum" NOT NULL, "description" character varying(255) NOT NULL, CONSTRAINT "UQ_017943867ed5ceef9c03edd9745" UNIQUE ("key"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "department_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "department_id" uuid NOT NULL, "permission_id" uuid NOT NULL, "granted" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_251eca408083656bd32934072fc" UNIQUE ("department_id", "permission_id"), CONSTRAINT "PK_6b87d692008c3080116a529f08b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_9b7ca6d30b94fef571cff876884" UNIQUE ("name"), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "description" text, "responsible_user_id" uuid, "isActive" boolean NOT NULL DEFAULT true, "home_organization_id" uuid, "hasFullOrganizationAccess" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_8681da666ad9699d568b3e91064" UNIQUE ("name"), CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_notificationpreference_enum" AS ENUM('EMAIL_ONLY', 'INTERNAL_ONLY', 'BOTH')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "login" character varying(100) NOT NULL, "email" character varying(150) NOT NULL, "passwordHash" character varying(255) NOT NULL, "department_id" uuid, "isActive" boolean NOT NULL DEFAULT true, "isAdmin" boolean NOT NULL DEFAULT false, "notificationPreference" "public"."users_notificationpreference_enum" NOT NULL DEFAULT 'BOTH', "mutedNotificationTypes" text array NOT NULL DEFAULT '{}', "lastLoginAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2d443082eccd5198f95f2a36e2" ON "users" ("login") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "tokenHash" character varying(255) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "ipAddress" character varying(60), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_approvals_decision_enum" AS ENUM('APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "purchase_approvals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_request_id" uuid NOT NULL, "approver_id" uuid NOT NULL, "approver_department_id" uuid NOT NULL, "decision" "public"."purchase_approvals_decision_enum" NOT NULL, "reason" text, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e5b4932af67ddd238939482fd20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_id" uuid NOT NULL, "author_id" uuid NOT NULL, "content" text NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "followers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_id" uuid NOT NULL, "user_id" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_e74ad4ae873d059b35562d8210e" UNIQUE ("ticket_id", "user_id"), CONSTRAINT "PK_c90cfc5b18edd29bd15ba95c1a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'RESOLVED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "protocol" character varying(20) NOT NULL, "title" character varying(200) NOT NULL, "description" text NOT NULL, "purchase_request_id" uuid NOT NULL, "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'PENDING', "priority" "public"."tickets_priority_enum" NOT NULL DEFAULT 'MEDIUM', "assignee_id" uuid, "department_id" uuid NOT NULL, "organization_id" uuid, "requester_id" uuid NOT NULL, "is_archived" boolean NOT NULL DEFAULT false, "archived_at" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "REL_9c315b3cfb6020ce11d3708f69" UNIQUE ("purchase_request_id"), CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e4b65de8df5eb74ee4734fdf9b" ON "tickets" ("protocol") `);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_id" uuid, "purchase_request_id" uuid, "originalName" character varying(255) NOT NULL, "physicalName" character varying(255) NOT NULL, "path" text NOT NULL, "mimeType" character varying(120) NOT NULL, "size" bigint NOT NULL, "is_invoice_note" boolean NOT NULL DEFAULT false, "uploaded_by_id" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_requests_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_requests_status_enum" AS ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "purchase_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "number" character varying(20) NOT NULL, "department_id" uuid NOT NULL, "organization_id" uuid, "requester_id" uuid NOT NULL, "costCenter" character varying(100) NOT NULL, "supplier" character varying(150) NOT NULL, "category" character varying(100) NOT NULL, "description" text NOT NULL, "justification" text NOT NULL, "estimatedValue" numeric(14,2) NOT NULL, "priority" "public"."purchase_requests_priority_enum" NOT NULL DEFAULT 'MEDIUM', "observations" text, "status" "public"."purchase_requests_status_enum" NOT NULL DEFAULT 'DRAFT', "approved_at" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f3c5a8ff7bd4338f4c860925c8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e5cb0c449b139de4c5cf8949c5" ON "purchase_requests" ("number") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('NEW_TICKET', 'NEW_COMMENT', 'NEW_ATTACHMENT', 'NEW_INVOICE_NOTE', 'TICKET_MOVED', 'TICKET_RESOLVED', 'TICKET_CANCELLED', 'TICKET_REOPENED', 'NEW_FOLLOWER', 'REQUEST_APPROVED', 'REQUEST_REJECTED', 'REQUEST_PENDING_APPROVAL')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(200) NOT NULL, "message" text NOT NULL, "link" character varying(255), "isRead" boolean NOT NULL DEFAULT false, "related_ticket_id" uuid, "related_purchase_request_id" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."history_action_enum" AS ENUM('CREATED', 'COMMENTED', 'ATTACHMENT_ADDED', 'ATTACHMENT_REMOVED', 'PRIORITY_CHANGED', 'STATUS_CHANGED', 'ASSIGNEE_CHANGED', 'CANCELLED', 'REOPENED', 'RESOLVED', 'APPROVED', 'REJECTED', 'FOLLOWER_ADDED', 'FOLLOWER_REMOVED', 'SUBMITTED_FOR_APPROVAL', 'ARCHIVED', 'UNARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticket_id" uuid, "purchase_request_id" uuid, "user_id" uuid NOT NULL, "action" "public"."history_action_enum" NOT NULL, "description" text NOT NULL, "metadata" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9384942edf4804b38ca0ee51416" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4b93183a93e6df9ed355ab6edb" ON "history" ("ticket_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8964b32622f7b357a44e40a2c" ON "history" ("purchase_request_id") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'UPLOAD', 'DOWNLOAD', 'COMMENT', 'MOVE', 'STATUS_CHANGE', 'PERMISSION_CHANGE')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "action" "public"."audit_logs_action_enum" NOT NULL, "entity" character varying(100) NOT NULL, "entityId" character varying(100), "ipAddress" character varying(60), "metadata" jsonb, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(100) NOT NULL, "value" jsonb NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c8639b7626fa94ba8265628f214" UNIQUE ("key"), CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "department_organization_access" ("department_id" uuid NOT NULL, "organization_id" uuid NOT NULL, CONSTRAINT "PK_ddaf7ebed0444649a4cd9bd3a7c" PRIMARY KEY ("department_id", "organization_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40f1bea59da5fcb6c50f1e5f99" ON "department_organization_access" ("department_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7b29609f1fd05c90f6f88a2c0" ON "department_organization_access" ("organization_id") `);
        await queryRunner.query(`ALTER TABLE "department_permissions" ADD CONSTRAINT "FK_6a604945ba103f0e74f996cdc3b" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department_permissions" ADD CONSTRAINT "FK_39e312446f4735d5bda8497ed13" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_a37d72ae26acb6f86512f1b8681" FOREIGN KEY ("responsible_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_658d84fc3f80a1ed80c91b212d5" FOREIGN KEY ("home_organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_0921d1972cf861d568f5271cd85" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_approvals" ADD CONSTRAINT "FK_2bd102ea7d9b517542a71f5b3f3" FOREIGN KEY ("purchase_request_id") REFERENCES "purchase_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_approvals" ADD CONSTRAINT "FK_154209b80628e3edf9d9fc54b63" FOREIGN KEY ("approver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_approvals" ADD CONSTRAINT "FK_3f633be84c48a451d0d487d4598" FOREIGN KEY ("approver_department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_be8180d9b44a05e449b85f5b773" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "followers" ADD CONSTRAINT "FK_2a5cd2b465bfffd58cc2f1c5f2c" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "followers" ADD CONSTRAINT "FK_d6e6e6be11ffefd40e60bffbebd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_9c315b3cfb6020ce11d3708f69a" FOREIGN KEY ("purchase_request_id") REFERENCES "purchase_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_dff6e2b44c9b5e177114588772f" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_fb1d03aa5fffa0e5ca41873a00a" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_613ef43a793c628ad7b22981f33" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_2a06f5cdaf003ceaa9fcf08be77" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_73d871f247ffebda5dc3f0df8a4" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_b0be09ca4cbbb52d1a5d5cce94d" FOREIGN KEY ("purchase_request_id") REFERENCES "purchase_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_70a38fc450d3b433c86b67e69d6" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_requests" ADD CONSTRAINT "FK_3ee8e94c75dcdbe9029954d0f87" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_requests" ADD CONSTRAINT "FK_1a4a911011345738f6c1c27d93a" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_requests" ADD CONSTRAINT "FK_f4a79f7b7ce5945c1c2f7e07174" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "history" ADD CONSTRAINT "FK_ea92daa642af67e2a924a5547d5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "department_organization_access" ADD CONSTRAINT "FK_40f1bea59da5fcb6c50f1e5f997" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "department_organization_access" ADD CONSTRAINT "FK_f7b29609f1fd05c90f6f88a2c06" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "department_organization_access" DROP CONSTRAINT "FK_f7b29609f1fd05c90f6f88a2c06"`);
        await queryRunner.query(`ALTER TABLE "department_organization_access" DROP CONSTRAINT "FK_40f1bea59da5fcb6c50f1e5f997"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "history" DROP CONSTRAINT "FK_ea92daa642af67e2a924a5547d5"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "purchase_requests" DROP CONSTRAINT "FK_f4a79f7b7ce5945c1c2f7e07174"`);
        await queryRunner.query(`ALTER TABLE "purchase_requests" DROP CONSTRAINT "FK_1a4a911011345738f6c1c27d93a"`);
        await queryRunner.query(`ALTER TABLE "purchase_requests" DROP CONSTRAINT "FK_3ee8e94c75dcdbe9029954d0f87"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_70a38fc450d3b433c86b67e69d6"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_b0be09ca4cbbb52d1a5d5cce94d"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_73d871f247ffebda5dc3f0df8a4"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_2a06f5cdaf003ceaa9fcf08be77"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_613ef43a793c628ad7b22981f33"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_fb1d03aa5fffa0e5ca41873a00a"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_dff6e2b44c9b5e177114588772f"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_9c315b3cfb6020ce11d3708f69a"`);
        await queryRunner.query(`ALTER TABLE "followers" DROP CONSTRAINT "FK_d6e6e6be11ffefd40e60bffbebd"`);
        await queryRunner.query(`ALTER TABLE "followers" DROP CONSTRAINT "FK_2a5cd2b465bfffd58cc2f1c5f2c"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e6d38899c31997c45d128a8973b"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_be8180d9b44a05e449b85f5b773"`);
        await queryRunner.query(`ALTER TABLE "purchase_approvals" DROP CONSTRAINT "FK_3f633be84c48a451d0d487d4598"`);
        await queryRunner.query(`ALTER TABLE "purchase_approvals" DROP CONSTRAINT "FK_154209b80628e3edf9d9fc54b63"`);
        await queryRunner.query(`ALTER TABLE "purchase_approvals" DROP CONSTRAINT "FK_2bd102ea7d9b517542a71f5b3f3"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_0921d1972cf861d568f5271cd85"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_658d84fc3f80a1ed80c91b212d5"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_a37d72ae26acb6f86512f1b8681"`);
        await queryRunner.query(`ALTER TABLE "department_permissions" DROP CONSTRAINT "FK_39e312446f4735d5bda8497ed13"`);
        await queryRunner.query(`ALTER TABLE "department_permissions" DROP CONSTRAINT "FK_6a604945ba103f0e74f996cdc3b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7b29609f1fd05c90f6f88a2c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40f1bea59da5fcb6c50f1e5f99"`);
        await queryRunner.query(`DROP TABLE "department_organization_access"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8964b32622f7b357a44e40a2c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b93183a93e6df9ed355ab6edb"`);
        await queryRunner.query(`DROP TABLE "history"`);
        await queryRunner.query(`DROP TYPE "public"."history_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5cb0c449b139de4c5cf8949c5"`);
        await queryRunner.query(`DROP TABLE "purchase_requests"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_requests_priority_enum"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4b65de8df5eb74ee4734fdf9b"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP TABLE "followers"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "purchase_approvals"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_approvals_decision_enum"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d443082eccd5198f95f2a36e2"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_notificationpreference_enum"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP TABLE "department_permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_key_enum"`);
    }

}
